easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Article
        - App\Entity\Comment
        - App\Entity\Game
        - App\Entity\Picture
        - App\Entity\Test
        - App\Entity\Topic
        - App\Entity\User
