easy_admin:
    site_name: 'Video Gaming Lovers'
    
    entities:
      Article:
        class: App\Entity\Article
      Comment:
        class: App\Entity\Comment
      Game:
        class: App\Entity\Game
      Picture:
        class: App\Entity\Picture
      Test:
        class: App\Entity\Test
      Topic:
        class: App\Entity\Topic
      User:
        class: App\Entity\User
